### ISSUE TITLE
v3.4.2 REXML::ParseException: #<NoMethodError: undefined method 'eof?' for nil>

### ISSUE THREAD

**Issue by Epigene** [ruby/rexml#290]
Hello!

We're seeing an error when upgrading from v3.4.1 to v3.4.2 in cobertura coverage generator.
```
Formatter SimpleCov::Formatter::CoberturaFormatter failed with REXML::ParseException: #<NoMethodError: undefined method 'eof?' for nil>
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/source.rb:275:in 'REXML::IOSource#read_until'
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/parsers/baseparser.rb:731:in 'REXML::Parsers::BaseParser#process_comment'
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/parsers/baseparser.rb:457:in 'REXML::Parsers::BaseParser#pull_event'
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/parsers/baseparser.rb:249:in 'REXML::Parsers::BaseParser#pull'
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/parsers/treeparser.rb:21:in 'REXML::Parsers::TreeParser#parse'
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/document.rb:466:in 'REXML::Document#build'
/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/document.rb:103:in 'REXML::Document#initialize'
/ruby-3.4.4/gems/simplecov-cobertura-2.1.0/lib/simplecov-cobertura.rb:37:in 'Class#new'
/ruby-3.4.4/gems/simplecov-cobertura-2.1.0/lib/simplecov-cobertura.rb:37:in 'SimpleCov::Formatter::CoberturaFormatter#result_to_xml'
/ruby-3.4.4/gems/simplecov-cobertura-2.1.0/lib/simplecov-cobertura.rb:20:in 'SimpleCov::Formatter::CoberturaFormatter#format'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/formatter/multi_formatter.rb:9:in 'block in SimpleCov::Formatter::MultiFormatter::InstanceMethods#format'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/formatter/multi_formatter.rb:8:in 'Array#map'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/formatter/multi_formatter.rb:8:in 'SimpleCov::Formatter::MultiFormatter::InstanceMethods#format'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/formatter/multi_formatter.rb:9:in 'block in SimpleCov::Formatter::MultiFormatter::InstanceMethods#format'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/formatter/multi_formatter.rb:8:in 'Array#map'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/formatter/multi_formatter.rb:8:in 'SimpleCov::Formatter::MultiFormatter::InstanceMethods#format'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/result.rb:51:in 'SimpleCov::Result#format!'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/configuration.rb:197:in 'block in SimpleCov::Configuration#at_exit'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov.rb:189:in 'SimpleCov.run_exit_tasks!'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov.rb:179:in 'SimpleCov.at_exit_behavior'
/ruby-3.4.4/gems/simplecov-0.22.0/lib/simplecov/defaults.rb:30:in 'block in <top (required)>'
...
Exception parsing
Line: 3
Position: 214
Last 80 unconsumed characters:
 (/ruby-3.4.4/gems/rexml-3.4.2/lib/rexml/parsers/baseparser.rb:524:in 'REXML::Parsers::BaseParser#pull_event')
```

I don't think I'll be able to provide reproduction steps.

**Comment by kou** [comment]
Could you try the latest simplecov-cobertura?

See also:
* https://github.com/jessebs/simplecov-cobertura/pull/44
* https://github.com/ruby/rexml/issues/287
